name: Deploy

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == 'Approved' }}
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
      ci-run-number: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runNumber }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          token: ${{ secrets.APROVE_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated ðŸš€'
          
      - name: Get Issue Data
        uses: peter-murray/issue-body-parser-action@v2.0.1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.APROVE_TOKEN }}
          issue_id: ${{ github.event.issue.number }}         
          payload_marker: target_payload 
  
  deploy-dev:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'Dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create approval Issue for Prod
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.APROVE_TOKEN }}
          ENVIRONMENT: Prod
          RUNNUMBER: ${{ needs.parse.outputs.ci-run-number }}
        with:
          filename: .github/deployment-approval.md
      
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          github_token: ${{ secrets.APROVE_TOKEN }}
          workflow: docker-image.yml
          repo: wyldvan/Hello-World-Pigz
          run_number: ${{ needs.parse.outputs.ci-run-number }}
          name: 'your-artifact-name'
          path: ${{ github.workspace }}
          
      - name: Deploy to DEV
        run: echo Simulating Deployment    
          

    
  deploy-prod:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'Prod' }}
    runs-on: ubuntu-latest
    steps:
               
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          GITHUB_TOKEN: ${{ secrets.APROVE_TOKEN }}
          workflow: docker-image.yml
          repo: wyldvan/Hello-World-Pigz
          run_number: ${{ needs.parse.outputs.ci-run-number }}
          name: 'your-artifact-name'
          path: ${{ github.workspace }}
          
      - name: Deploy to PROD
        run: echo Simulating Deployment 

  close-issue:
    needs: [deploy-dev, deploy-prod]
    if: ${{ always() }}
    runs-on: ubuntu-latest  
    
    steps:
      - name: Close Issue
        if: ${{ needs.deploy-dev.result == 'success' || needs.deploy-prod.result == 'success' }}
        uses: peter-evans/close-issue@v3.0.1
        with:
          token: ${{ secrets.APROVE_TOKEN }}
          comment: 'Deployment Completed ðŸŒŸ'
