name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Build NGINX
      run: pwd && ls -latr &&  cd nginx && docker build . --file Dockerfile --tag wyldvan-nginx-app:$(date +%s) && cd .. 
    - name: Build PHP
      run: pwd && ls -latr && cd backend && docker build . --file Dockerfile --tag wyldvan-php-app:$(date +%s)  && cd ..  
    - name: Push to Registry
      run:  echo "Simulando envio para o registry:docker push wyldvan-nginx-app:$(date +%s) ,docker push wyldvan-php-app:$(date +%s) "
    - name: Deploy k8s
      run:  echo "Simulando deploy em k8s:kubectl set image deployment/nginx nginx=wyldvan-nginx-app:$(date +%s), kubectl set image deployment/php-app php-app:wyldvan-php-app:$(date +%s) "

    - name: Simulate a Build
      run: echo 'hello youtube' > output.txt

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: 'your-artifact-name'
        path: 'output.txt'

    - name: Create an issue
      uses: JasonEtco/create-an-issue@v2.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.APROVE_TOKEN }}
        ENVIRONMENT: Dev
        RUNNUMBER: ${{ github.run_number  }}
      with:         
          filename: .github/deployment-approval.md
